config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/patient/:patient_id/generaliste", to: "practitioners#generalist", as: "generalist"
  get "/patient/:patient_id/gynecologue", to: "practitioners#gynecologist", as: "gynecologist"
  get "/reading/:reading_id/antecedants", to: "first_forms#history", as: "history"
  post "/readings/:reading_id/first_forms/:first_form_id/breasts", to: "clinical_anomalies#breasts", as: "breasts"
  post "/readings/:reading_id/first_forms/:first_form_id/position/:clinical_anomaly_id", to: "clinical_anomalies#position", as: "position"
  get "/test", to: "pages#test", as: "test"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :patients, only: [:index, :new, :create] do
    resources :practitioners, only: [:create]
    resources :readings, only: [:new]
  end
  resources :readings, only: [] do
    resources :first_forms, only: [:new, :create] do
      resources :clinical_anomalies, only: [:index, :create, :delete]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinical_anomaly.rb
class ClinicalAnomaly < ApplicationRecord
  belongs_to :clinical_symptom
  belongs_to :first_form
end

app/models/clinical_symptom.rb
class ClinicalSymptom < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :patient
  belongs_to :practitioner
end

app/models/first_form.rb
class FirstForm < ApplicationRecord
  belongs_to :reading
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :sheet
  has_many :consultations
  has_many :practitioners, through: :consultations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  has_many :consultations
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/radio_symptom.rb
class RadioSymptom < ApplicationRecord
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
  belongs_to :sheet
  has_many :first_forms
end

app/models/second_form.rb
class SecondForm < ApplicationRecord
  belongs_to :reading
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :readings
  has_many :sheets, through: :readings
  has_many :patients, through: :sheets
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @patients = Patient.all
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to generalist_path(@patient)
    else
      render :new
    end
  end

  def patient_params
    params.require(:patient).permit(
    :first_name,
    :last_name,
    :maiden_name,
    :birth_date,
    :phone1,
    :phone2,
    :address,
    :city,
    :zip_code,
    :health_insurance,
    :social_security_number,
      )
  end
end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  before_action :find_patient, only: [ :generalist, :gynecologist, :create ]
  before_action :new_practitioner, only: [ :generalist, :gynecologist ]

  def generalist
    session["practitioner"] = :generalist
  end

  def gynecologist
    session["practitioner"] = :gynecologist
  end


  def create
    @practitioner = Practitioner.new(practitioner_params)
    if @practitioner.save
      Consultation.create(patient: @patient, practitioner: @practitioner)
      if @practitioner.speciality == "generalist"
        redirect_to gynecologist_path(@patient)
      else
        redirect_to new_patient_reading_path(@patient)
      end
    else
      render session["practitioner"]
    end
  end

  private

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end

  def new_practitioner
    @practitioner = Practitioner.new
  end

  def practitioner_params
    params.require(:practitioner).permit(
    :name,
    :speciality,
    :address,
    :city,
    :zip_code,
      )
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController

  def new
    @patient = Patient.find(params[:patient_id])
    @sheet = Sheet.create(patient: @patient)
    @reading = Reading.create(user: current_user, sheet:@sheet)
    redirect_to history_path(@reading)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/fist_forms_helper.rb
module FistFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/practitioners/generalist.html.erb
<div class="wrapper">
  <div class="container">
      <div class="row">
        <h1>Médecin généraliste</h1>
      </div>
      <%= simple_form_for @practitioner, url: patient_practitioners_path(@patient) do |f| %>
      <div class="row">
        <div class="col-xs-12 col-sm-4"><%= f.input :name, label: "Nom de famille" %></div>
        <div><%= f.input :speciality, input_html: { value: "generalist" }, as: :hidden %></div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4"><%= f.input :address, label: "Adresse" %></div>
        <div class="col-xs-12 col-sm-4"><%= f.input :city, label: "Commune" %></div>
        <div class="col-xs-12 col-sm-4"><%= f.input :zip_code, label: "Code postal" %></div>
      </div>
      <div class="row">
        <div class="col-sm-3 col-sm-offset-5"><%= f.button :submit, "Continuer", class: "btn btn-primary btn-lg" %></div>
      </div>
      <% end %>
  </div>
</div>

app/views/practitioners/gynecologist.html.erb
<div class="wrapper">
  <div class="container">
      <div class="row">
        <h1>Gynécologue</h1>
      </div>
      <%= simple_form_for @practitioner, url: patient_practitioners_path(@patient) do |f| %>
      <div class="row">
        <div class="col-xs-12 col-sm-4"><%= f.input :name, label: "Nom de famille" %></div>
        <div><%= f.input :speciality, input_html: { value: "gynecologist" }, as: :hidden %></div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4"><%= f.input :address, label: "Adresse" %></div>
        <div class="col-xs-12 col-sm-4"><%= f.input :city, label: "Commune" %></div>
        <div class="col-xs-12 col-sm-4"><%= f.input :zip_code, label: "Code postal" %></div>
      </div>
      <div class="row">
        <div class="col-sm-3 col-sm-offset-5"><%= f.button :submit, "Continuer", class: "btn btn-primary btn-lg" %></div>
      </div>
      <% end %>
  </div>
</div>