config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/patient/:patient_id/generaliste", to: "practitioners#generalist", as: "generalist"
  get "/patient/:patient_id/gynecologue", to: "practitioners#gynecologist", as: "gynecologist"
  get "/reading/:reading_id/antecedants", to: "first_forms#history", as: "history"
  post "/readings/:reading_id/first_forms/:first_form_id/breasts", to: "clinical_anomalies#breasts", as: "breasts"
  post "/readings/:reading_id/first_forms/:first_form_id/position/:clinical_anomaly_id", to: "clinical_anomalies#position", as: "position"
  get "/test", to: "pages#test", as: "test"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :patients, only: [:index, :new, :create] do
    resources :practitioners, only: [:create]
    resources :readings, only: [:new]
  end
  resources :readings, only: [] do
    resources :first_forms, only: [:new, :create] do
      resources :clinical_anomalies, only: [:index, :create, :delete]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinical_anomaly.rb
class ClinicalAnomaly < ApplicationRecord
  belongs_to :clinical_symptom
  belongs_to :first_form
end

app/models/clinical_symptom.rb
class ClinicalSymptom < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :patient
  belongs_to :practitioner
end

app/models/first_form.rb
class FirstForm < ApplicationRecord
  belongs_to :reading
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :sheet
  has_many :consultations
  has_many :practitioners, through: :consultations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  has_many :consultations
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/radio_symptom.rb
class RadioSymptom < ApplicationRecord
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
  belongs_to :sheet
  has_many :first_forms
end

app/models/second_form.rb
class SecondForm < ApplicationRecord
  belongs_to :reading
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :readings
  has_many :sheets, through: :readings
  has_many :patients, through: :sheets
end

app/controllers/clinical_anomalies_controller.rb
class ClinicalAnomaliesController < ApplicationController
  before_action :find_reading_first_form, only: [ :index, :breasts ]

  def index
    symptoms = ClinicalSymptom.all
    @symptoms = Hash.new
    symptoms.each do |s|
      a = ClinicalAnomaly.find_by(clinical_symptom: s, first_form: @first_form )
      @symptoms[s.name] = a ? a.position : nil
    end
  end

  def breasts
    @symptom = ClinicalSymptom.find_by(name: breasts_params[:selected] )
    @anomaly = ClinicalAnomaly.create(clinical_symptom: @symptom, first_form: @first_form )
  end

  def position
    @anomaly = ClinicalAnomaly.find(params[:clinical_anomaly_id])
    @anomaly.position = position_params[:selected]
    @anomaly.save
    redirect_to reading_first_form_clinical_anomalies_path(@anomaly.first_form.reading, @anomaly.first_form)
  end

  def delete
  end

  private

  def find_reading_first_form
    @reading = Reading.find(params[:reading_id])
    @first_form = FirstForm.find(params[:first_form_id])
  end

  def breasts_params
    # a paramétré
    params.require(:symptom).permit!
  end

  def position_params
    # a paramétré
    params.require(:position).permit!
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @patients = Patient.all
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to generalist_path(@patient)
    else
      render :new
    end
  end

  def patient_params
    params.require(:patient).permit(
    :first_name,
    :last_name,
    :maiden_name,
    :birth_date,
    :phone1,
    :phone2,
    :address,
    :city,
    :zip_code,
    :health_insurance,
    :social_security_number,
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinical_anomalies_helper.rb
module ClinicalAnomaliesHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/fist_forms_helper.rb
module FistFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/clinical_anomalies/breasts.html.erb
<div>
  <div class="container">
    <div class="row">
      <h2>Examen Clinique</h2>
    </div>
    <hr>
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="background-relative" style="background-image: url('http://res.cloudinary.com/dpilgpat0/image/upload/v1477558070/breasts_yzlqi1.png');">
          <div class="background-relative">
            <div class="right">
              <div class="circle">
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Droit NW" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-0" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Droit NE" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-90" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Droit SE" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-180" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Droit SW" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-270" %>
                <% end %>
              </div>
            </div>
            <div class="left">
              <div class="circle">
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Gauche NW" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-0" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Gauche NE" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-90" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Gauche SE" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-180" %>
                <% end %>
                <%= simple_form_for :position, url: position_path(@reading, @first_form, @anomaly), method: :post do |f| %>
                  <%= f.input :selected, input_html: { value: "Gauche SW" }, as: :hidden %>
                  <%= f.button :submit, "", class: "btn-quart btn-rotate-270" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <hr>
      <div>Sélectionner la zone concernée</div>
    </div>
  </div>
</div>

app/views/clinical_anomalies/index.html.erb
<div>
  <div class="container">
    <div class="row">
      <h2>Examen Clinique</h2>
    </div>
    <hr>
    <div class="row">
      <% @symptoms.each do |symptom, position| %>
        <% if position %>
          <div class="col-sm-4"><%= symptom %><hr></div>
          <div class="col-sm-2"><%= position %><hr></div>
        <% else %>
          <div class="col-sm-6">
            <div>
              <%= simple_form_for :symptom, url: breasts_path(@reading, @first_form), method: :post do |f| %>
                <%= f.input :selected, input_html: { value: symptom }, as: :hidden %>
                <%= f.button :submit, symptom, class: "btn"  %>
              <% end %>
              <hr>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>