config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/patient/:patient_id/generaliste", to: "practitioners#generalist", as: "generalist"
  get "/patient/:patient_id/gynecologue", to: "practitioners#gynecologist", as: "gynecologist"
  get "/reading/:reading_id/antecedants", to: "first_forms#history", as: "history"
  post "/readings/:reading_id/first_forms/:first_form_id/breasts", to: "clinical_anomalies#breasts", as: "breasts"
  post "/readings/:reading_id/first_forms/:first_form_id/position/:clinical_anomaly_id", to: "clinical_anomalies#position", as: "position"
  get "/test", to: "pages#test", as: "test"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :patients, only: [:index, :new, :create] do
    resources :practitioners, only: [:create]
    resources :readings, only: [:new]
  end
  resources :readings, only: [] do
    resources :first_forms, only: [:new, :create] do
      resources :clinical_anomalies, only: [:index, :create, :delete]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinical_anomaly.rb
class ClinicalAnomaly < ApplicationRecord
  belongs_to :clinical_symptom
  belongs_to :first_form
end

app/models/clinical_symptom.rb
class ClinicalSymptom < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :patient
  belongs_to :practitioner
end

app/models/first_form.rb
class FirstForm < ApplicationRecord
  belongs_to :reading
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :sheet
  has_many :consultations
  has_many :practitioners, through: :consultations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  has_many :consultations
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/radio_symptom.rb
class RadioSymptom < ApplicationRecord
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
  belongs_to :sheet
  has_many :first_forms
end

app/models/second_form.rb
class SecondForm < ApplicationRecord
  belongs_to :reading
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :readings
  has_many :sheets, through: :readings
  has_many :patients, through: :sheets
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @patients = Patient.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/fist_forms_helper.rb
module FistFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1>Liste des patients</h1>
      <hr>
    </div>
    <div class="row">
      <% @patients.each do |patient| %>
          <div class="col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://phen375-france.fr/wp-content/uploads/2016/09/cancer-du-sein-phen375-france.jpg');">
              <div class="card-category"><% "#{patient.sheet.count} consultations" %></div>
              <div class="card-description">
                <h2><%= "#{patient.first_name} #{patient.last_name}" %></h2>
                <% if patient.sheet && patient.sheet.last %>
                  <p><%= "Date de la dernière consultation : #{patient.sheet.last.created_at}" %></p>
                <% end %>
              </div>
              <%= image_tag "profil.png", class: "card-user avatar" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.9) 0%, rgba(0,36,61,0.9) 50%), url('http://www.lonelyplanet.fr/sites/default/files/styles/slideshow_destination/public/images_lpi/2014-06-26/fotolia_58295601_subscription_monthly_m.jpg?itok=_v3zjPTc');">
  <div class="banner-content">
    <h1>agwadec</h1>
    <h2>Association Guadeloupéenne pour le depistage des cancers</h2>
    <p>Fiche d'interprétation</p>
    <%= link_to "1ère Lecture", new_patient_path, class: "btn btn-primary btn-lg" %>
    <a class="btn btn-primary btn-lg">2ème Lecture</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-grey">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <p>Contactez nous</p>
          <p>06 18 23 73 31</p>
        </div>
        <div class="col-xs-12 col-sm-1">
          <i class="fa fa-facebook"></i>
        </div>
        <div class="col-xs-12 col-sm-1">
          <i class="fa fa-twitter"></i>
        </div>
        <div class="col-xs-12 col-sm-1">
          <i class="fa fa-envelope-o"></i>
        </div>
        <div class="col-xs-12 col-sm-1">
          <i class="fa fa-mobile"></i>
        </div>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Chercher un patient">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "profil.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>