config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/patient/:patient_id/generaliste", to: "practitioners#generalist", as: "generalist"
  get "/patient/:patient_id/gynecologue", to: "practitioners#gynecologist", as: "gynecologist"
  get "/reading/:reading_id/antecedants", to: "first_forms#history", as: "history"
  post "/readings/:reading_id/first_forms/:first_form_id/breasts", to: "clinical_anomalies#breasts", as: "breasts"
  post "/readings/:reading_id/first_forms/:first_form_id/position/:clinical_anomaly_id", to: "clinical_anomalies#position", as: "position"
  get "/test", to: "pages#test", as: "test"
  get "/dashboard", to: "pages#dashboard", as: "dashboard"

  resources :patients, only: [:index, :new, :create] do
    resources :practitioners, only: [:create]
    resources :readings, only: [:new]
  end
  resources :readings, only: [] do
    resources :first_forms, only: [:new, :create] do
      resources :clinical_anomalies, only: [:index, :create, :delete]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinical_anomaly.rb
class ClinicalAnomaly < ApplicationRecord
  belongs_to :clinical_symptom
  belongs_to :first_form
end

app/models/clinical_symptom.rb
class ClinicalSymptom < ApplicationRecord
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :patient
  belongs_to :practitioner
end

app/models/first_form.rb
class FirstForm < ApplicationRecord
  belongs_to :reading
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :sheet
  has_many :consultations
  has_many :practitioners, through: :consultations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  has_many :consultations
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/radio_symptom.rb
class RadioSymptom < ApplicationRecord
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
  belongs_to :sheet
  has_many :first_forms
end

app/models/second_form.rb
class SecondForm < ApplicationRecord
  belongs_to :reading
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :readings
  has_many :sheets, through: :readings
  has_many :patients, through: :sheets
end

app/controllers/first_forms_controller.rb
class FirstFormsController < ApplicationController
  before_action :find_reading, only: [ :history, :create ]

  def history
    @first_form = FirstForm.new
    session["method"] = :history
  end

  def create
    @first_form = FirstForm.new(first_form_params)
    @first_form.reading = @reading
    if @first_form.save
      redirect_to reading_first_form_clinical_anomalies_path(@reading, @first_form)
    else
      render session["method"]
    end
  end

  private

  def find_reading
    @reading = Reading.find(params[:reading_id])
  end

  def first_form_params
    params.require(:first_form).permit(
    :mammography_type,
    :mammography_system,
    :past_mammography,
    :past_mammography_date,
    :past_operation,
    :past_operation_date,
    :past_operation_reason,
    :family_history,
    :family_member,
    :hormonal_treatment,
    :clinical_examen_refusal,
    :normal_right,
    :normal_left,
    :abnormal_right,
    :abnormal_left,
    :technical_difficulty,
    :cad,
    :additional_impact,
    :normal_mammography,
    :echography_suspect,
    :echography_suspect_description,
    :abnormal_mammography_refusal,
    :radio_anomaly,
    :clinical_anomaly,
    :zoom,
    :echography,
    :cytoponction,
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @patients = Patient.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/fist_forms_helper.rb
module FistFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/first_forms/history.html.erb
<div>
  <div class="container">
      <div class="row">
        <h2>Type de mammographie</h2>
      </div>
      <%= simple_form_for @first_form, url: reading_first_forms_path(@reading) do |f| %>
      <div class="row">
        <div class="col-sm-6"><%= f.input :mammography_type, label: "Type de mammographie", collection: [ "Mammographe analogique", "Mammographe numérique DR plein champ ou balayage", "Mammographe numérique Système Numérique CR" ] %></div>
        <div class="col-sm-6"><%= f.input :mammography_system, label: "Marque et système" %></div>
      </div>
      <hr>
      <div class="row">
        <h2>Antécédents</h2>
      </div>
      <div class="row">
        <div class="col-sm-6"><%= f.input :past_mammography, label: "Avez-vous déjà passé une mammographie ?" %></div>
        <div class="col-sm-6"><%= f.input :past_operation, label: "Avez-vous déjà été opérée ?" %></div>
        <div class="col-sm-6"><%= f.input :past_mammography_date, label: "À quelle date ?" %></div>
        <div class="col-sm-6"><%= f.input :past_operation_date, label: "À quelle date ?" %></div>
        <div class="col-sm-6"><%= f.input :past_operation_reason, label: "Pour quel motif ?" %></div>
      </div>
      <div class="row">
        <div class="col-sm-6"><%= f.input :family_history, label: "Antécédants familiaux" %></div>
        <div class="col-sm-6"><%= f.input :family_member, label: "Membre de la famille" %></div>
        <div class="col-sm-6"><%= f.input :hormonal_treatment, label: "Traitement hormonal" %></div>
        <div class="col-sm-2 col-sm-offset-4"><%= f.button :submit, "Continuer", class: "btn btn-primary btn-lg" %></div>
      </div>
      <% end %>
  </div>
</div>